### ISSUE TITLE
ALLOW_USER_PASSWORD_AUTH not being set

### ISSUE THREAD

**Issue by morgler** [michaelduminy/serverless-cognito-add-custom-attributes#12]
I try to set allow the USER_PASSWORD_AUTH for my Cognito client:

```
CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:custom.userPoolName}-client
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH #=ADMIN_NO_SRP_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      ReadAttributes:
        - email
        - name
        - picture
        - locale
        - preferred_username
      WriteAttributes:
        - email
        - name
        - picture
        - locale
        - preferred_username
```

All other `ExplicitAuthFlows` are set correctly (or maybe they're just the defaults?), except for `ALLOW_USER_PASSWORD_AUTH`. I tried various ways of naming this flow, but its never checked in the user pool.

Am I missing something?
